In [1]:
from apyori import apriori

In [2]:
import pandas as pd

In [3]:
orders = pd.read_csv("A:\Frequently bought togher\instacart_2017_05_01\orders.csv")
orders

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0
11,2168274,2,prior,1,2,11,NaN
12,1501582,2,prior,2,5,10,10.0
13,1901567,2,prior,3,1,10,3.0
14,738281,2,prior,4,2,10,8.0
15,1673511,2,prior,5,3,11,8.0
16,1199898,2,prior,6,2,9,13.0
17,3194192,2,prior,7,2,12,14.0
18,788338,2,prior,8,1,15,27.0
19,1718559,2,prior,9,2,9,8.0
20,1447487,2,prior,10,1,11,6.0
21,1402090,2,prior,11,1,10,30.0
22,3186735,2,prior,12,1,9,28.0
23,3268552,2,prior,13,4,11,30.0
24,839880,2,prior,14,3,10,13.0
25,1492625,2,train,15,1,11,30.0
26,1374495,3,prior,1,1,14,NaN
27,444309,3,prior,2,3,19,9.0
28,3002854,3,prior,3,3,16,21.0
29,2037211,3,prior,4,2,18,20.0
...,...,...,...,...,...,...,...
3421053,2789700,206208,prior,35,3,22,4.0
3421054,844592,206208,prior,36,6,15,10.0
3421055,1541132,206208,prior,37,2,12,3.0
3421056,2808240,206208,prior,38,0,15,19.0
3421057,3027766,206208,prior,39,2,14,9.0
3421058,3356245,206208,prior,40,5,9,10.0
3421059,442304,206208,prior,41,2,14,11.0
3421060,2675140,206208,prior,42,1,19,6.0
3421061,167903,206208,prior,43,4,14,3.0
3421062,2393201,206208,prior,44,6,16,2.0
3421063,3292671,206208,prior,45,2,11,3.0
3421064,3059777,206208,prior,46,1,10,13.0
3421065,2239861,206208,prior,47,3,4,9.0
3421066,1285346,206208,prior,48,1,11,5.0
3421067,1882108,206208,prior,49,1,22,7.0
3421068,803273,206208,test,50,5,11,4.0
3421069,3154581,206209,prior,1,3,11,NaN
3421070,1889163,206209,prior,2,3,17,7.0
3421071,1542354,206209,prior,3,5,11,30.0
3421072,688306,206209,prior,4,1,10,30.0
3421073,2307371,206209,prior,5,4,15,3.0
3421074,3186442,206209,prior,6,0,16,3.0
3421075,550836,206209,prior,7,2,13,9.0
3421076,2129269,206209,prior,8,3,17,22.0
3421077,2558525,206209,prior,9,4,15,22.0
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [4]:
orders.dtypes

order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [5]:
products = pd.read_csv("A:\Frequently bought togher\instacart_2017_05_01\products.csv")
products

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13
5,6,Dry Nose Oil,11,11
6,7,Pure Coconut Water With Orange,98,7
7,8,Cut Russet Potatoes Steam N' Mash,116,1
8,9,Light Strawberry Blueberry Yogurt,120,16
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7
10,11,Peach Mango Juice,31,7
11,12,Chocolate Fudge Layer Cake,119,1
12,13,Saline Nasal Mist,11,11
13,14,Fresh Scent Dishwasher Cleaner,74,17
14,15,Overnight Diapers Size 6,56,18
15,16,Mint Chocolate Flavored Syrup,103,19
16,17,Rendered Duck Fat,35,12
17,18,Pizza for One Suprema Frozen Pizza,79,1
18,19,Gluten Free Quinoa Three Cheese & Mushroom Blend,63,9
19,20,Pomegranate Cranberry & Aloe Vera Enrich Drink,98,7
20,21,Small & Medium Dental Dog Treats,40,8
21,22,Fresh Breath Oral Rinse Mild Mint,20,11
22,23,Organic Turkey Burgers,49,12
23,24,Tri-Vi-Sol® Vitamins A-C-and D Supplement Drop...,47,11
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19
25,26,Fancy Feast Trout Feast Flaked Wet Cat Food,41,8
26,27,Complete Spring Water Foaming Antibacterial Ha...,127,11
27,28,Wheat Chex Cereal,121,14
28,29,Fresh Cut Golden Sweet No Salt Added Whole Ker...,81,15
29,30,"Three Cheese Ziti, Marinara with Meatballs",38,1
...,...,...,...,...
49658,49659,Organic Creamed Coconut,17,13
49659,49660,Professionals Sleek Shampoo,22,11
49660,49661,Porto,134,5
49661,49662,Bacon Cheddar Pretzel Pieces,107,19
49662,49663,Ultra Protein Power Crunch Peanut Butter N' Ho...,57,14
49663,49664,Lemon Cayenne Drinking Vinegar,100,21
49664,49665,Super Dark Coconut Ash & Banana Chocolate Bar,45,19
49665,49666,Ginger Snaps Snacking Cookies,61,19
49666,49667,Enchilada with Spanish Rice & Beans Meal,38,1
49667,49668,Apple Cinnamon Scented Candles,101,17
49668,49669,K Cup Dark Blend,100,21
49669,49670,Beef Summer Sausage,106,12
49670,49671,Milk Chocolate Drops,45,19
49671,49672,Cafe Mocha K-Cup Packs,26,7
49672,49673,Stone Baked Multi Grain Artisan Rolls,129,1
49673,49674,Frozen Greek Yogurt Bars Chocolate Chip,37,1
49674,49675,Cinnamon Dolce Keurig Brewed K Cups,26,7
49675,49676,Ultra Red Energy Drink,64,7
49676,49677,Thick & Chunky Sloppy Joe Sauce,59,15
49677,49678,Large Chicken & Cheese Taquitos,129,1
49678,49679,Famous Chocolate Wafers,61,19
49679,49680,All Natural Creamy Caesar Dressing,89,13
49680,49681,Spaghetti with Meatballs and Sauce Meal,38,1
49681,49682,California Limeade,98,7
49682,49683,Cucumber Kirby,83,4
49683,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5
49684,49685,En Croute Roast Hazelnut Cranberry,42,1
49685,49686,Artisan Baguette,112,3
49686,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8
49687,49688,Fresh Foaming Cleanser,73,11

In [6]:
products.product_id.nunique()

49688

In [7]:
products.product_name.nunique()

49688

In [8]:
orders_products_prior = pd.read_csv("A:\Frequently bought togher\instacart_2017_05_01\order_products__prior.csv")
orders_products_prior

          order_id  product_id  add_to_cart_order  reordered
0                2       33120                  1          1
1                2       28985                  2          1
2                2        9327                  3          0
3                2       45918                  4          1
4                2       30035                  5          0
5                2       17794                  6          1
6                2       40141                  7          1
7                2        1819                  8          1
8                2       43668                  9          0
9                3       33754                  1          1
10               3       24838                  2          1
11               3       17704                  3          1
12               3       21903                  4          1
13               3       17668                  5          1
14               3       46667                  6          1
15               3       17461                  7          1
16               3       32665                  8          1
17               4       46842                  1          0
18               4       26434                  2          1
19               4       39758                  3          1
20               4       27761                  4          1
21               4       10054                  5          1
22               4       21351                  6          1
23               4       22598                  7          1
24               4       34862                  8          1
25               4       40285                  9          1
26               4       17616                 10          1
27               4       25146                 11          1
28               4       32645                 12          1
29               4       41276                 13          1
...            ...         ...                ...        ...
32434459   3421080       41950                  4          0
32434460   3421080       31717                  5          0
32434461   3421080       12935                  6          1
32434462   3421080       25122                  7          0
32434463   3421080       10667                  8          0
32434464   3421080       38061                  9          0
32434465   3421081       38185                  1          0
32434466   3421081       12218                  2          0
32434467   3421081       32299                  3          0
32434468   3421081        3060                  4          0
32434469   3421081       20539                  5          0
32434470   3421081       35221                  6          0
32434471   3421081       12861                  7          0
32434472   3421082       17279                  1          1
32434473   3421082       12738                  2          1
32434474   3421082       16797                  3          0
32434475   3421082       43352                  4          1
32434476   3421082       32700                  5          1
32434477   3421082       12023                  6          0
32434478   3421082       47941                  7          0
32434479   3421083        7854                  1          0
32434480   3421083       45309                  2          0
32434481   3421083       21162                  3          0
32434482   3421083       18176                  4          1
32434483   3421083       35211                  5          0
32434484   3421083       39678                  6          1
32434485   3421083       11352                  7          0
32434486   3421083        4600                  8          0
32434487   3421083       24852                  9          1
32434488   3421083        5020                 10          1

[32434489 rows x 4 columns]

In [9]:
orders_products_prior.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [10]:
orders_products_train = pd.read_csv("A:\Frequently bought togher\instacart_2017_05_01\order_products__train.csv")
orders_products_train

         order_id  product_id  add_to_cart_order  reordered
0               1       49302                  1          1
1               1       11109                  2          1
2               1       10246                  3          0
3               1       49683                  4          0
4               1       43633                  5          1
5               1       13176                  6          0
6               1       47209                  7          0
7               1       22035                  8          1
8              36       39612                  1          0
9              36       19660                  2          1
10             36       49235                  3          0
11             36       43086                  4          1
12             36       46620                  5          1
13             36       34497                  6          1
14             36       48679                  7          1
15             36       46979                  8          1
16             38       11913                  1          0
17             38       18159                  2          0
18             38        4461                  3          0
19             38       21616                  4          1
20             38       23622                  5          0
21             38       32433                  6          0
22             38       28842                  7          0
23             38       42625                  8          0
24             38       39693                  9          0
25             96       20574                  1          1
26             96       30391                  2          0
27             96       40706                  3          1
28             96       25610                  4          0
29             96       27966                  5          1
...           ...         ...                ...        ...
1384587   3421026       32237                  3          0
1384588   3421026          10                  4          0
1384589   3421026        4493                  5          0
1384590   3421026        7781                  6          0
1384591   3421049       40800                  1          0
1384592   3421049       17706                  2          0
1384593   3421049       33424                  3          1
1384594   3421049       17299                  4          0
1384595   3421049       26800                  5          0
1384596   3421049       34243                  6          0
1384597   3421056        5750                  1          1
1384598   3421056        9340                  2          1
1384599   3421056       21709                  3          1
1384600   3421056       16475                  4          0
1384601   3421056       12432                  5          0
1384602   3421058       15629                  1          1
1384603   3421058        4347                  2          1
1384604   3421058       34466                  3          1
1384605   3421058        6244                  4          1
1384606   3421058        6858                  5          1
1384607   3421058       30316                  6          1
1384608   3421058       35578                  7          0
1384609   3421058       32650                  8          1
1384610   3421063       49235                  1          1
1384611   3421063       13565                  2          1
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[1384617 rows x 4 columns]

In [11]:
orders_products_train.shape

(1384617, 4)

In [12]:
orders_products_prior.shape

(32434489, 4)

In [13]:
sample_orders = orders_products_prior.head(1000000)
#sample_orders = orders_products_prior.copy()
sample_orders =  sample_orders.merge(orders,on='order_id')
sample_orders.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2,33120,1,1,202279,prior,3,5,9,8.0
1,2,28985,2,1,202279,prior,3,5,9,8.0
2,2,9327,3,0,202279,prior,3,5,9,8.0
3,2,45918,4,1,202279,prior,3,5,9,8.0
4,2,30035,5,0,202279,prior,3,5,9,8.0

In [14]:
sample_orders = sample_orders.merge(products,on='product_id')
sample_orders.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id
0,2,33120,1,1,202279,prior,3,5,9,8.0,Organic Egg Whites,86,16
1,26,33120,5,0,153404,prior,2,0,16,7.0,Organic Egg Whites,86,16
2,120,33120,13,0,23750,prior,11,6,8,10.0,Organic Egg Whites,86,16
3,327,33120,5,1,58707,prior,21,6,9,8.0,Organic Egg Whites,86,16
4,390,33120,28,1,166654,prior,48,0,12,9.0,Organic Egg Whites,86,16

In [15]:
sample_orders.product_name.value_counts()

Banana                                                                           14759
Bag of Organic Bananas                                                           11867
Organic Strawberries                                                              8138
Organic Baby Spinach                                                              7477
Organic Hass Avocado                                                              6551
Organic Avocado                                                                   5379
Large Lemon                                                                       4700
Strawberries                                                                      4388
Limes                                                                             4317
Organic Raspberries                                                               4238
Organic Whole Milk                                                                4153
Organic Yellow Onion                                                              3446
Organic Garlic                                                                    3376
Organic Zucchini                                                                  3244
Organic Blueberries                                                               3121
Cucumber Kirby                                                                    2981
Organic Fuji Apple                                                                2739
Organic Lemon                                                                     2735
Apple Honeycrisp Organic                                                          2625
Organic Grape Tomatoes                                                            2568
Seedless Red Grapes                                                               2531
Honeycrisp Apple                                                                  2505
Organic Half & Half                                                               2477
Organic Cucumber                                                                  2455
Organic Baby Carrots                                                              2358
Organic Gala Apples                                                               2341
Sparkling Water Grapefruit                                                        2304
Organic Large Extra Fancy Fuji Apple                                              2296
Carrots                                                                           2268
Organic Baby Arugula                                                              2224
                                                                                 ...
Dry Arbol Peppers                                                                    1
California Peach Lowfat Yogurt                                                       1
Bread Crumbs, Plain                                                                  1
Orange Mango Naturally Flavored Sparkling Water                                      1
Organic Pure Cane Sugar                                                              1
Fiesta Blend Vegetables                                                              1
Tri-Color Penne Pasta                                                                1
Multigrain Sandwich Rounds                                                           1
Gf Cheddar Organic Otg                                                               1
Decorating Green Cake Icing                                                          1
Allergy 24 Hour 10mg Posted 10/28/2013 Dissolve Tabs                                 1
Smartblend True Instinct Turkey & Venison Dog Food                                   1
Antioxidant Super Tea Pomegranate Honey Green Tea                                    1
Jambalaya Original Rice Mix                                                          1
Chef's Cut, Tomatoes with Basil Leaf                                                 1
Overnight Pads with Wings                                                            1
Wasabi Sauce                                                                         1
Whiskey, Tennessee Honey, Original Recipe                                            1
Soothing with Aloe Body Lotion                                                       1
Petite Crab Cakes                                                                    1
Meyer Ginger Lemonade                                                                1
Coffee Cake                                                                          1
French Onion Dip Potato Crisps                                                       1
Thermal Creations Heat Tamer Leave-In Spray                                          1
Air Effects Febreze Air Effects with Downy April Fresh Air Freshener Air Care        1
Roasted Ground Coriander                                                             1
Sweet & Creamy Regular Medium Roast Iced K-Cups Arabica Coffee                       1
Fruit Smoothies SPF 15 Lip Protectant                                                1
Black Bean, Organic, Spaghetti Shape                                                 1
Crab Meat Backfin Lump                                                               1
Name: product_name, Length: 35098, dtype: int64

In [16]:
sample_orders.shape

(1000000, 13)

In [17]:
sample_orders.order_id.nunique()

99260

In [18]:
sample_orders.product_id.nunique()

35098

In [19]:
sample_orders.dtypes

order_id                    int64
product_id                  int64
add_to_cart_order           int64
reordered                   int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
product_name               object
aisle_id                    int64
department_id               int64
dtype: object

In [20]:
sample_orders2 = sample_orders.groupby(['order_id','product_name'],as_index=False)['product_id'].count()
#sample_orders2 = sample_orders2.pivot_table(index = ['order_id'], columns='product_name',values='product_id',aggfunc= lambda x: x).reset_index()
#.fillna(0)
#.unstack().fillna(0)
sample_orders2 = sample_orders2.iloc[:,:-1]

In [21]:
sample_orders2.head(2)

   order_id                              product_name
0         2  All Natural No Stir Creamy Almond Butter
1         2                                   Carrots

In [22]:
pd.get_dummies(sample_orders2['product_name'])

MemoryError:

In [23]:
market_basket = sample_orders.groupby('order_id')['product_name'].apply(list)
market_basket = market_basket.reset_index()
market_basket

       order_id                                       product_name
0             2  [Organic Egg Whites, Michigan Organic Kale, Ga...
1             3  [Total 2% with Strawberry Lowfat Greek Straine...
2             4  [Plain Pre-Sliced Bagels, Honey/Lemon Cough Dr...
3             5  [Bag of Organic Bananas, Just Crisp, Parmesan,...
4             6  [Cleanse, Dryer Sheets Geranium Scent, Clean D...
5             7                   [Orange Juice, Pineapple Chunks]
6             8                    [Original Hawaiian Sweet Rolls]
7             9  [Organic Red Radish, Bunch, Whole White Mushro...
8            10  [Green Beans, Banana, Baby Portabella Mushroom...
9            11  [Extra Virgin Olive Oil, Teriyaki & Pineapple ...
10           12  [French Vanilla Coffee Creamer, 2% Milk, Cheru...
11           13  [Light, Chunky Salsa Medium, Handmade Vodka Fr...
12           14  [Hair Bender Whole Bean Coffee, Organic Whole ...
13           15  [Spring Water, Organic Extra Virgin Olive Oil,...
14           16  [Original Popcorn, Water, Sea Salt Made With O...
15           18  [Organic Raspberries, Organic Avocado, 100% Re...
16           19  [Unsweetened Almondmilk, Organic Baby Carrots,...
17           20  [Banana, Nilla Wafers, Mini Chocolate Chip Waf...
18           21  [Yuba Tofu Skin, Organic Firm Tofu, Frozen Org...
19           22  [2% Reduced Fat Milk, Banana, Asparagus, Butte...
20           23  [Organic Avocado, Organic Baby Spinach Salad, ...
21           24  [Strawberry Lemonade Frozen Pops, Mint Chocola...
22           25  [Original Popcorn, Boomchickapop Sweet & Salty...
23           26  [Organic Egg Whites, Organic Baby Spinach, Ban...
24           27  [Michigan Organic Kale, Carrots, Bag of Organi...
25           28  [Air Chilled Organic Boneless Skinless Chicken...
26           29  [Bag of Organic Bananas, Raspberries, Smartwat...
27           30  [Synergy Organic Kombucha Gingerberry, Mango C...
28           31  [Organic Baby Spinach, Organic Cilantro, Earl ...
29           32  [Bag of Organic Bananas, Organic Bread with 21...
...         ...                                                ...
99230    105598  [Organic Bosc Pear, Green Bell Pepper, Organic...
99231    105599  [Whole Bean French Roast Dark Roast Blend Extr...
99232    105600  [Carrots, Seedless Watermelon, European Cucumb...
99233    105601  [Organic Avocado, Roasted & Salted Almonds, Cu...
99234    105602  [Bag of Organic Bananas, Extra Virgin Olive Oi...
99235    105603  [Indian Mattar Paneer, Indian Paneer Tikka, Ch...
99236    105604  [Bag of Organic Bananas, Everyday  Facial Tiss...
99237    105605  [White Sugar Free Peppermint Gum, Non-Drowsy O...
99238    105607  [Organic Raspberries, Organic Avocado, Organic...
99239    105608  [Organic Raspberries, Organic Strawberries, Or...
99240    105609  [Bag of Organic Bananas, Organic Hass Avocado,...
99241    105610  [Beef Franks, Organic 2% Reduced Fat Milk, Min...
99242    105611  [Ultra Soft Facial Tissues, Shepherd's Pie, Pe...
99243    105612  [Sparkling Water Grapefruit, Deli Fresh Honey ...
99244    105613  [Bag of Organic Bananas, Organic Raspberries, ...
99245    105614  [Large Lemon, Limes, Chocolate Chip Cookies, C...
99246    105615  [Organic Strawberries, Cold Brew Coffee, Potat...
99247    105616  [Bag of Organic Bananas, Organic Cilantro, Org...
99248    105617  [Organic Strawberries, Honeycrisp Apple, Limes...
99249    105618  [Organic Baby Spinach, Organic Whole Milk, Bon...
99250    105619  [Sparkling Water Grapefruit, Blackberry Cucumb...
99251    105620  [Organic Ginger Root, White Corn, Red Peppers,...
99252    105622  [Bag of Organic Bananas, Organic Baby Carrots,...
99253    105623  [Boneless Skinless Chicken Breast Fillets, Cle...
99254    105624  [Cold Brew Coffee, Cage Free Large White Eggs,...
99255    105625  [Dinner Classic White 10.375\" Dinner Plate, O...
99256    105626  [Non Fat Greek Yogurt, Liquid Egg Whites, Orga...
99257    105627  [Organic Shredded Mozzarella, Organic Chopped ...
99258    105628  [Bag of Organic Bananas, Organic Gala Apples, ...
99259    105629  [Organic Baby Spinach, Organic Raspberries, Ba...

[99260 rows x 2 columns]

In [66]:
market_basket['product_name']

0        ['Organic Egg Whites', 'Michigan Organic Kale'...
1        ['Total 2% with Strawberry Lowfat Greek Strain...
2        ['Plain Pre-Sliced Bagels', 'Honey/Lemon Cough...
3        ['Bag of Organic Bananas', 'Just Crisp, Parmes...
4        ['Cleanse', 'Dryer Sheets Geranium Scent', 'Cl...
5                     ['Orange Juice', 'Pineapple Chunks']
6                        ['Original Hawaiian Sweet Rolls']
7        ['Organic Red Radish, Bunch', 'Whole White Mus...
8        ['Green Beans', 'Banana', 'Baby Portabella Mus...
9        ['Extra Virgin Olive Oil', 'Teriyaki & Pineapp...
10       ['French Vanilla Coffee Creamer', '2% Milk', '...
11       ['Light', 'Chunky Salsa Medium', 'Handmade Vod...
12       ['Hair Bender Whole Bean Coffee', 'Organic Who...
13       ['Spring Water', 'Organic Extra Virgin Olive O...
14       ['Original Popcorn', 'Water', 'Sea Salt Made W...
15       ['Organic Raspberries', 'Organic Avocado', '10...
16       ['Unsweetened Almondmilk', 'Organic Baby Carro...
17       ['Banana', 'Nilla Wafers', 'Mini Chocolate Chi...
18       ['Yuba Tofu Skin', 'Organic Firm Tofu', 'Froze...
19       ['2% Reduced Fat Milk', 'Banana', 'Asparagus',...
20       ['Organic Avocado', 'Organic Baby Spinach Sala...
21       ['Strawberry Lemonade Frozen Pops', 'Mint Choc...
22       ['Original Popcorn', 'Boomchickapop Sweet & Sa...
23       ['Organic Egg Whites', 'Organic Baby Spinach',...
24       ['Michigan Organic Kale', 'Carrots', 'Bag of O...
25       ['Air Chilled Organic Boneless Skinless Chicke...
26       ['Bag of Organic Bananas', 'Raspberries', 'Sma...
27       ['Synergy Organic Kombucha Gingerberry', 'Mang...
28       ['Organic Baby Spinach', 'Organic Cilantro', '...
29       ['Bag of Organic Bananas', 'Organic Bread with...
                               ...
99230    ['Organic Bosc Pear', 'Green Bell Pepper', "Or...
99231    ['Whole Bean French Roast Dark Roast Blend Ext...
99232    ['Carrots', 'Seedless Watermelon', 'European C...
99233    ['Organic Avocado', 'Roasted & Salted Almonds'...
99234    ['Bag of Organic Bananas', 'Extra Virgin Olive...
99235    ['Indian Mattar Paneer', 'Indian Paneer Tikka'...
99236    ['Bag of Organic Bananas', 'Everyday  Facial T...
99237    ['White Sugar Free Peppermint Gum', 'Non-Drows...
99238    ['Organic Raspberries', 'Organic Avocado', 'Or...
99239    ['Organic Raspberries', 'Organic Strawberries'...
99240    ['Bag of Organic Bananas', 'Organic Hass Avoca...
99241    ['Beef Franks', 'Organic 2% Reduced Fat Milk',...
99242    ['Ultra Soft Facial Tissues', "Shepherd's Pie"...
99243    ['Sparkling Water Grapefruit', 'Deli Fresh Hon...
99244    ['Bag of Organic Bananas', 'Organic Raspberrie...
99245    ['Large Lemon', 'Limes', 'Chocolate Chip Cooki...
99246    ['Organic Strawberries', 'Cold Brew Coffee', '...
99247    ['Bag of Organic Bananas', 'Organic Cilantro',...
99248    ['Organic Strawberries', 'Honeycrisp Apple', '...
99249    ['Organic Baby Spinach', 'Organic Whole Milk',...
99250    ['Sparkling Water Grapefruit', 'Blackberry Cuc...
99251    ['Organic Ginger Root', 'White Corn', 'Red Pep...
99252    ['Bag of Organic Bananas', 'Organic Baby Carro...
99253    ['Boneless Skinless Chicken Breast Fillets', '...
99254    ['Cold Brew Coffee', 'Cage Free Large White Eg...
99255    ['Dinner Classic White 10.375\\" Dinner Plate'...
99256    ['Non Fat Greek Yogurt', 'Liquid Egg Whites', ...
99257    ['Organic Shredded Mozzarella', 'Organic Chopp...
99258    ['Bag of Organic Bananas', 'Organic Gala Apple...
99259    ['Organic Baby Spinach', 'Organic Raspberries'...
Name: product_name, Length: 99260, dtype: object

In [24]:
sample_orders[sample_orders.order_id == 10557]

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id
107014,10557,19660,3,1,186847,prior,43,5,12,4.0,Spring Water,115,7
339152,10557,30489,4,1,186847,prior,43,5,12,4.0,Original Hummus,67,20
741065,10557,343,5,0,186847,prior,43,5,12,4.0,Organic Whole Peeled Baby Carrots,123,4
823795,10557,42803,1,1,186847,prior,43,5,12,4.0,Organic Apple Slices,50,19
938513,10557,23198,2,1,186847,prior,43,5,12,4.0,Organic Chicken Drumsticks,49,12

In [25]:
mb = market_basket.product_name.values

In [26]:
mb

array([list(['Organic Egg Whites', 'Michigan Organic Kale', 'Garlic Powder', 'Coconut Butter', 'Natural Sweetener', 'Carrots', 'Original Unflavored Gelatine Mix', 'All Natural No Stir Creamy Almond Butter', 'Classic Blend Cole Slaw']),
       list(['Total 2% with Strawberry Lowfat Greek Strained Yogurt', 'Unsweetened Almondmilk', 'Lemons', 'Organic Baby Spinach', 'Unsweetened Chocolate Almond Breeze Almond Milk', 'Organic Ginger Root', 'Air Chilled Organic Boneless Skinless Chicken Breasts', 'Organic Ezekiel 49 Bread Cinnamon Raisin']),
       list(['Plain Pre-Sliced Bagels', 'Honey/Lemon Cough Drops', 'Chewy 25% Low Sugar Chocolate Chip Granola', 'Oats & Chocolate Chewy Bars', "Kellogg's Nutri-Grain Apple Cinnamon Cereal", 'Nutri-Grain Soft Baked Strawberry Cereal Breakfast Bars', "Kellogg's Nutri-Grain Blueberry Cereal", 'Tiny Twists Pretzels', 'Traditional Snack Mix', 'Goldfish Cheddar Baked Snack Crackers', 'Original Orange Juice', 'Sugarfree Energy Drink', 'Energy Drink']),
       ...,
       list(['Organic Shredded Mozzarella', 'Organic Chopped Spinach', 'Organic Pumpkin', 'Low Fat Strawberry Yogurt Tubes', 'Cream Top Smooth Coffee Yogurt', 'Organic Vanilla Extract', 'Liquid Hand Soap, Refill, Lemon Verbena Scent', 'Dark Chocolate Morsels', 'Certified Compostable Large Baking Cups', 'Gluten Free Baking & Packing Mix', 'Roasted Garlic Extra Virgin Olive Oil']),
       list(['Bag of Organic Bananas', 'Organic Gala Apples', 'Apple Honeycrisp Organic', 'Almond Breeze Original Almond Milk', 'Light Semisoft Cheese']),
       list(['Organic Baby Spinach', 'Organic Raspberries', 'Banana', 'Organic Strawberries', 'Boneless Skinless Chicken Breasts', 'No Salt Added Black Beans', 'Organic White Basmati Rice', 'Original Enriched Rice Drink', 'Organic Short Grain Brown Rice', 'Organic Broccoli Crowns', 'Oat Blueberry Lemon Whenever Bars', 'Original Bar BBQ Sauce', '80% Lean Ground Beef'])],
      dtype=object)

In [27]:
newmb = []
for i in mb:
    newmb.append(i)
newmb[:5]

[['Organic Egg Whites',
  'Michigan Organic Kale',
  'Garlic Powder',
  'Coconut Butter',
  'Natural Sweetener',
  'Carrots',
  'Original Unflavored Gelatine Mix',
  'All Natural No Stir Creamy Almond Butter',
  'Classic Blend Cole Slaw'],
 ['Total 2% with Strawberry Lowfat Greek Strained Yogurt',
  'Unsweetened Almondmilk',
  'Lemons',
  'Organic Baby Spinach',
  'Unsweetened Chocolate Almond Breeze Almond Milk',
  'Organic Ginger Root',
  'Air Chilled Organic Boneless Skinless Chicken Breasts',
  'Organic Ezekiel 49 Bread Cinnamon Raisin'],
 ['Plain Pre-Sliced Bagels',
  'Honey/Lemon Cough Drops',
  'Chewy 25% Low Sugar Chocolate Chip Granola',
  'Oats & Chocolate Chewy Bars',
  "Kellogg's Nutri-Grain Apple Cinnamon Cereal",
  'Nutri-Grain Soft Baked Strawberry Cereal Breakfast Bars',
  "Kellogg's Nutri-Grain Blueberry Cereal",
  'Tiny Twists Pretzels',
  'Traditional Snack Mix',
  'Goldfish Cheddar Baked Snack Crackers',
  'Original Orange Juice',
  'Sugarfree Energy Drink',
  'Energy Drink'],
 ['Bag of Organic Bananas',
  'Just Crisp, Parmesan',
  'Fresh Fruit Salad',
  'Organic Raspberries',
  '2% Reduced Fat Milk',
  'Sensitive Toilet Paper',
  'Natural Artesian Water, Mini & Mobile',
  'Matzos, Thin, Tea',
  'Boneless Skinless Chicken Breast Fillets',
  'Mini Original Babybel Cheese',
  'Macaroni And Cheese',
  'Clementines',
  "Biscuits Orange Pim's",
  'Dairy Milk Fruit & Nut Chocolate Bar',
  'Artichokes',
  'Apricot Preserves',
  'One Ply Choose A Size Big Roll Paper Towel Rolls',
  'Wafer, Chocolate',
  'French Lavender Hand Wash',
  'American Slices Cheese',
  'Everyday  Facial Tissues',
  'Organic Hass Avocado',
  'Spaghetti Pasta',
  'Meyer Lemon',
  'Bag of Organic Lemons',
  'Original Black Box Tablewater Cracker'],
 ['Cleanse',
  'Dryer Sheets Geranium Scent',
  'Clean Day Lavender Scent Room Freshener Spray']]

In [75]:
list(apriori(newmb, min_support=0.00045, min_confidence=0.2, min_lift=2, min_length=2))

KeyboardInterrupt:

In [71]:
ar = list(apriori(newmb, min_support=0.00045, min_confidence=0.2, min_lift=2, min_length=2))
ar = pd.DataFrame(ar)
ar

,items,support,ordered_statistics
0,"(Apple Honeycrisp Organic, Bag of Organic Bana...",0.007193,"[((Apple Honeycrisp Organic), (Bag of Organic ..."
1,"(Organic Cucumber, Bag of Organic Bananas)",0.006488,"[((Organic Cucumber), (Bag of Organic Bananas)..."
2,"(Organic D'Anjou Pears, Bag of Organic Bananas)",0.004665,"[((Organic D'Anjou Pears), (Bag of Organic Ban..."
3,"(Organic Gala Apples, Bag of Organic Bananas)",0.006589,"[((Organic Gala Apples), (Bag of Organic Banan..."
4,"(Organic Hass Avocado, Bag of Organic Bananas)",0.019101,"[((Organic Hass Avocado), (Bag of Organic Bana..."
5,"(Organic Kiwi, Bag of Organic Bananas)",0.004554,"[((Organic Kiwi), (Bag of Organic Bananas), 0...."
6,"(Organic Large Extra Fancy Fuji Apple, Bag of ...",0.007264,"[((Organic Large Extra Fancy Fuji Apple), (Bag..."
7,"(Organic Lemon, Bag of Organic Bananas)",0.007344,"[((Organic Lemon), (Bag of Organic Bananas), 0..."
8,"(Organic Raspberries, Bag of Organic Bananas)",0.012795,"[((Organic Raspberries), (Bag of Organic Banan..."
9,"(Organic Tomato Cluster, Bag of Organic Bananas)",0.004866,"[((Organic Tomato Cluster), (Bag of Organic Ba..."
10,"(Blueberries, Banana)",0.005531,"[((Blueberries), (Banana), 0.3041551246537396,..."
11,"(Boneless Skinless Chicken Breasts, Banana)",0.004685,"[((Boneless Skinless Chicken Breasts), (Banana..."
12,"(Cucumber Kirby, Banana)",0.009893,"[((Cucumber Kirby), (Banana), 0.32941965783294..."
13,"(Banana, Honeycrisp Apple)",0.009007,"[((Honeycrisp Apple), (Banana), 0.356886227544..."
14,"(Organic Avocado, Banana)",0.016593,"[((Organic Avocado), (Banana), 0.3061907417735..."
15,"(Banana, Organic Fuji Apple)",0.010326,"[((Organic Fuji Apple), (Banana), 0.3742241694..."
16,"(Seedless Red Grapes, Banana)",0.007727,"[((Seedless Red Grapes), (Banana), 0.303042275..."
17,"(Organic Cilantro, Limes)",0.005460,"[((Organic Cilantro), (Limes), 0.2562647754137..."
18,"(Organic Cucumber, Organic Baby Spinach)",0.005057,"[((Organic Cucumber), (Organic Baby Spinach), ..."
19,"(Organic Zucchini, Organic Baby Spinach)",0.006619,"[((Organic Zucchini), (Organic Baby Spinach), ..."
20,"(Organic Strawberries, Organic Blueberries)",0.007203,"[((Organic Blueberries), (Organic Strawberries..."
21,"(Organic Hass Avocado, Organic Cucumber)",0.005289,"[((Organic Cucumber), (Organic Hass Avocado), ..."
22,"(Organic Garlic, Organic Yellow Onion)",0.006820,"[((Organic Garlic), (Organic Yellow Onion), 0...."
23,"(Organic Lemon, Organic Hass Avocado)",0.006982,"[((Organic Lemon), (Organic Hass Avocado), 0.2..."
24,"(Organic Large Extra Fancy Fuji Apple, Organic...",0.004785,"[((Organic Large Extra Fancy Fuji Apple), (Org..."
25,"(Organic Raspberries, Organic Strawberries)",0.010115,"[((Organic Raspberries), (Organic Strawberries..."
26,"(Organic Whole String Cheese, Organic Strawber...",0.004604,"[((Organic Whole String Cheese), (Organic Stra..."

In [74]:
ar.iloc[24,:]['items']

frozenset({'Organic Large Extra Fancy Fuji Apple', 'Organic Strawberries'})

In [67]:
market_basket[(market_basket.product_name.str.contains('Organic Garlic'))& (market_basket['product_name'].str.contains('Organic Yellow Onion'))].shape

(706, 2)

In [68]:
market_basket[(market_basket.product_name.str.contains('Organic Garlic'))].shape

(3741, 2)

In [70]:
market_basket[(market_basket.product_name.str.contains('Organic Yellow Onion'))].shape

(3468, 2)

In [69]:
market_basket.shape

(99260, 2)

In [30]:
ar.iloc[0,-1]

[OrderedStatistic(items_base=frozenset({'Apple Honeycrisp Organic'}), items_add=frozenset({'Bag of Organic Bananas'}), confidence=0.27199999999999996, lift=2.2751091261481413)]

In [31]:
import re
def conf(x):
    return re.findall(r'\d+[.]\d+',x)

In [32]:
ar['ordered_statistics'] = ar['ordered_statistics'].astype('str')
ar['Confidence1'] = ar.ordered_statistics.apply(conf)

In [33]:
ar

,items,support,ordered_statistics,Confidence1
0,"(Apple Honeycrisp Organic, Bag of Organic Bana...",0.007193,[OrderedStatistic(items_base=frozenset({'Apple...,"[0.27199999999999996, 2.2751091261481413]"
1,"(Organic Cucumber, Bag of Organic Bananas)",0.006488,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.26232179226069247, 2.194156998381759]"
2,"(Organic D'Anjou Pears, Bag of Organic Bananas)",0.004665,"[OrderedStatistic(items_base=frozenset({""Organ...","[0.2949044585987261, 2.4666905334549214]"
3,"(Organic Gala Apples, Bag of Organic Bananas)",0.006589,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.279367791542076, 2.336736073857459]"
4,"(Organic Hass Avocado, Bag of Organic Bananas)",0.019101,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.28942146237215693, 2.4208287145074827]"
5,"(Organic Kiwi, Bag of Organic Bananas)",0.004554,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.2952318745917701, 2.469429162549852]"
6,"(Organic Large Extra Fancy Fuji Apple, Bag of ...",0.007264,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.31402439024390244, 2.6266167502831173]"
7,"(Organic Lemon, Bag of Organic Bananas)",0.007344,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.26654478976234003, 2.2294797195424176]"
8,"(Organic Raspberries, Bag of Organic Bananas)",0.012795,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.2996696554978764, 2.506548411959148]"
9,"(Organic Tomato Cluster, Bag of Organic Bananas)",0.004866,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.24150000000000002, 2.019995786635207]"
10,"(Blueberries, Banana)",0.005531,[OrderedStatistic(items_base=frozenset({'Blueb...,"[0.3041551246537396, 2.0455611947374615]"
11,"(Boneless Skinless Chicken Breasts, Banana)",0.004685,[OrderedStatistic(items_base=frozenset({'Bonel...,"[0.2996134020618557, 2.015016348577803]"
12,"(Cucumber Kirby, Banana)",0.009893,[OrderedStatistic(items_base=frozenset({'Cucum...,"[0.32941965783294197, 2.2154749804524574]"
13,"(Banana, Honeycrisp Apple)",0.009007,[OrderedStatistic(items_base=frozenset({'Honey...,"[0.3568862275449102, 2.400198316017873]"
14,"(Organic Avocado, Banana)",0.016593,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.3061907417735638, 2.0592515094819395]"
15,"(Banana, Organic Fuji Apple)",0.010326,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.3742241694048923, 2.5168027003949867]"
16,"(Seedless Red Grapes, Banana)",0.007727,[OrderedStatistic(items_base=frozenset({'Seedl...,"[0.303042275780324, 2.0380768543908774]"
17,"(Organic Cilantro, Limes)",0.005460,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.2562647754137116, 5.89224961954251]"
18,"(Organic Cucumber, Organic Baby Spinach)",0.005057,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.2044806517311609, 2.7145579097010875]"
19,"(Organic Zucchini, Organic Baby Spinach)",0.006619,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.20252774352651046, 2.688632315426164]"
20,"(Organic Strawberries, Organic Blueberries)",0.007203,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.22909323934636336, 2.7942731552617386]"
21,"(Organic Hass Avocado, Organic Cucumber)",0.005289,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.21384928716904275, 3.240219851076047]"
22,"(Organic Garlic, Organic Yellow Onion)",0.006820,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.20053317535545023, 5.776239984266393]"
23,"(Organic Lemon, Organic Hass Avocado)",0.006982,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.25338208409506396, 3.8392162520647304]"
24,"(Organic Large Extra Fancy Fuji Apple, Organic...",0.004785,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.2068815331010453, 2.5233547524710933]"
25,"(Organic Raspberries, Organic Strawberries)",0.010115,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.23690420009438415, 2.8895442247933856]"
26,"(Organic Whole String Cheese, Organic Strawber...",0.004604,[OrderedStatistic(items_base=frozenset({'Organ...,"[0.24756229685807152, 3.0195420970916906]"

In [54]:
new_df = ar.copy()

In [55]:
new_df['items']

0     (Apple Honeycrisp Organic, Bag of Organic Bana...
1            (Organic Cucumber, Bag of Organic Bananas)
2       (Organic D'Anjou Pears, Bag of Organic Bananas)
3         (Organic Gala Apples, Bag of Organic Bananas)
4        (Organic Hass Avocado, Bag of Organic Bananas)
5                (Organic Kiwi, Bag of Organic Bananas)
6     (Organic Large Extra Fancy Fuji Apple, Bag of ...
7               (Organic Lemon, Bag of Organic Bananas)
8         (Organic Raspberries, Bag of Organic Bananas)
9      (Organic Tomato Cluster, Bag of Organic Bananas)
10                                (Blueberries, Banana)
11          (Boneless Skinless Chicken Breasts, Banana)
12                             (Cucumber Kirby, Banana)
13                           (Banana, Honeycrisp Apple)
14                            (Organic Avocado, Banana)
15                         (Banana, Organic Fuji Apple)
16                        (Seedless Red Grapes, Banana)
17                            (Organic Cilantro, Limes)
18             (Organic Cucumber, Organic Baby Spinach)
19             (Organic Zucchini, Organic Baby Spinach)
20          (Organic Strawberries, Organic Blueberries)
21             (Organic Hass Avocado, Organic Cucumber)
22               (Organic Garlic, Organic Yellow Onion)
23                (Organic Lemon, Organic Hass Avocado)
24    (Organic Large Extra Fancy Fuji Apple, Organic...
25          (Organic Raspberries, Organic Strawberries)
26    (Organic Whole String Cheese, Organic Strawber...
Name: items, dtype: object

In [34]:
ar['confidence'] = ar.Confidence1.apply(lambda x:x[0][:4])
ar['lift'] = ar.Confidence1.apply(lambda x:x[1][0:4])
ar.drop(['Confidence1','ordered_statistics'],inplace = True,axis = 1)
ar

,items,support,confidence,lift
0,"(Apple Honeycrisp Organic, Bag of Organic Bana...",0.007193,0.27,2.27
1,"(Organic Cucumber, Bag of Organic Bananas)",0.006488,0.26,2.19
2,"(Organic D'Anjou Pears, Bag of Organic Bananas)",0.004665,0.29,2.46
3,"(Organic Gala Apples, Bag of Organic Bananas)",0.006589,0.27,2.33
4,"(Organic Hass Avocado, Bag of Organic Bananas)",0.019101,0.28,2.42
5,"(Organic Kiwi, Bag of Organic Bananas)",0.004554,0.29,2.46
6,"(Organic Large Extra Fancy Fuji Apple, Bag of ...",0.007264,0.31,2.62
7,"(Organic Lemon, Bag of Organic Bananas)",0.007344,0.26,2.22
8,"(Organic Raspberries, Bag of Organic Bananas)",0.012795,0.29,2.50
9,"(Organic Tomato Cluster, Bag of Organic Bananas)",0.004866,0.24,2.01
10,"(Blueberries, Banana)",0.005531,0.30,2.04
11,"(Boneless Skinless Chicken Breasts, Banana)",0.004685,0.29,2.01
12,"(Cucumber Kirby, Banana)",0.009893,0.32,2.21
13,"(Banana, Honeycrisp Apple)",0.009007,0.35,2.40
14,"(Organic Avocado, Banana)",0.016593,0.30,2.05
15,"(Banana, Organic Fuji Apple)",0.010326,0.37,2.51
16,"(Seedless Red Grapes, Banana)",0.007727,0.30,2.03
17,"(Organic Cilantro, Limes)",0.005460,0.25,5.89
18,"(Organic Cucumber, Organic Baby Spinach)",0.005057,0.20,2.71
19,"(Organic Zucchini, Organic Baby Spinach)",0.006619,0.20,2.68
20,"(Organic Strawberries, Organic Blueberries)",0.007203,0.22,2.79
21,"(Organic Hass Avocado, Organic Cucumber)",0.005289,0.21,3.24
22,"(Organic Garlic, Organic Yellow Onion)",0.006820,0.20,5.77
23,"(Organic Lemon, Organic Hass Avocado)",0.006982,0.25,3.83
24,"(Organic Large Extra Fancy Fuji Apple, Organic...",0.004785,0.20,2.52
25,"(Organic Raspberries, Organic Strawberries)",0.010115,0.23,2.88
26,"(Organic Whole String Cheese, Organic Strawber...",0.004604,0.24,3.01

In [35]:
ar.dtypes

items          object
support       float64
confidence     object
lift           object
dtype: object

In [36]:
ar.confidence = ar.confidence.astype('float')
ar.lift = ar.lift.astype('float')
ar.sort_values('confidence',ascending = [0])

,items,support,confidence,lift
15,"(Banana, Organic Fuji Apple)",0.010326,0.37,2.51
13,"(Banana, Honeycrisp Apple)",0.009007,0.35,2.40
12,"(Cucumber Kirby, Banana)",0.009893,0.32,2.21
6,"(Organic Large Extra Fancy Fuji Apple, Bag of ...",0.007264,0.31,2.62
16,"(Seedless Red Grapes, Banana)",0.007727,0.30,2.03
14,"(Organic Avocado, Banana)",0.016593,0.30,2.05
10,"(Blueberries, Banana)",0.005531,0.30,2.04
2,"(Organic D'Anjou Pears, Bag of Organic Bananas)",0.004665,0.29,2.46
5,"(Organic Kiwi, Bag of Organic Bananas)",0.004554,0.29,2.46
8,"(Organic Raspberries, Bag of Organic Bananas)",0.012795,0.29,2.50
11,"(Boneless Skinless Chicken Breasts, Banana)",0.004685,0.29,2.01
4,"(Organic Hass Avocado, Bag of Organic Bananas)",0.019101,0.28,2.42
0,"(Apple Honeycrisp Organic, Bag of Organic Bana...",0.007193,0.27,2.27
3,"(Organic Gala Apples, Bag of Organic Bananas)",0.006589,0.27,2.33
1,"(Organic Cucumber, Bag of Organic Bananas)",0.006488,0.26,2.19
7,"(Organic Lemon, Bag of Organic Bananas)",0.007344,0.26,2.22
17,"(Organic Cilantro, Limes)",0.005460,0.25,5.89
23,"(Organic Lemon, Organic Hass Avocado)",0.006982,0.25,3.83
9,"(Organic Tomato Cluster, Bag of Organic Bananas)",0.004866,0.24,2.01
26,"(Organic Whole String Cheese, Organic Strawber...",0.004604,0.24,3.01
25,"(Organic Raspberries, Organic Strawberries)",0.010115,0.23,2.88
20,"(Organic Strawberries, Organic Blueberries)",0.007203,0.22,2.79
21,"(Organic Hass Avocado, Organic Cucumber)",0.005289,0.21,3.24
18,"(Organic Cucumber, Organic Baby Spinach)",0.005057,0.20,2.71
19,"(Organic Zucchini, Organic Baby Spinach)",0.006619,0.20,2.68
22,"(Organic Garlic, Organic Yellow Onion)",0.006820,0.20,5.77
24,"(Organic Large Extra Fancy Fuji Apple, Organic...",0.004785,0.20,2.52

In [61]:
market_basket[market_basket['product_name'].str.contains('Organic Fuji Apple')].shape

(3066, 2)

In [65]:
market_basket[market_basket['product_name'].str.contains(r'Banana')].shape

(0, 2)

In [52]:
market_basket.shape

(99260, 2)

In [39]:
market_basket.head(2)

   order_id                                       product_name
0         2  [Organic Egg Whites, Michigan Organic Kale, Ga...
1         3  [Total 2% with Strawberry Lowfat Greek Straine...

In [50]:
market_basket.product_name = market_basket.product_name.astype('str')

In [51]:
market_basket[(market_basket.product_name.str.contains('Banana'))& (market_basket['product_name'].str.contains('Organic Fuji Apple'))].shape

(1583, 2)

In [42]:
market_basket[(market_basket.product_name.str.contains('Banana'))].shape

(29449, 2)

In [43]:
market_basket.order_id.nunique()

99260

In [44]:
29449/99260

0.2966854724964739

In [45]:
1583/99260

0.015948015313318558

In [46]:
0.016/0.30

0.05333333333333334

In [47]:
ar.shape

(27, 4)

In [48]:
ar.Confidence1[0]

AttributeError: 'DataFrame' object has no attribute 'Confidence1'

In [49]:
def conf(x):
    return x.str.split(',')[0][0].replace('[','')

In [77]:
ar['Confidence1'] = ar['Confidence1'].astype('str')
ar['Confidence'] = ar['Confidence1'].apply(conf)
#ar['lift'] = ar['Confidence1'].str.split(',')[0][1].replace(']','')
ar

,items,support,ordered_statistics,Confidence1,Confidence,lift
0,"(Lime Sparkling Water, Sparkling Water Grapefr...",0.004616,[OrderedStatistic(items_base=frozenset({'Lime ...,"['0.2893081761006289', '11.963673373522273']","[0.2893081761006289, 11.963673373522273]",'11.963673373522273'
1,"(Limes, Organic Cilantro)",0.005318,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.25728155339805825', '6.1049237170596395']","[0.25728155339805825, 6.1049237170596395]",'11.963673373522273'
2,"(Organic Zucchini, Organic Baby Spinach)",0.006723,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.2302405498281787', '3.1780849301767717']","[0.2302405498281787, 3.1780849301767717]",'11.963673373522273'
3,"(Organic Hass Avocado, Organic Cucumber)",0.005619,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.22764227642276422', '3.5448170731707314']","[0.22764227642276422, 3.5448170731707314]",'11.963673373522273'
4,"(Organic Hass Avocado, Organic Lemon)",0.006422,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.23272727272727273', '3.624']","[0.23272727272727273, 3.624]",'11.963673373522273'

In [83]:
def conf2(x):
    return x[0][0]

In [84]:
ar['Confidence2'] = ar['Confidence'].apply(conf)

In [85]:
ar

,items,support,ordered_statistics,Confidence1,Confidence,lift,Confidence2
0,"(Lime Sparkling Water, Sparkling Water Grapefr...",0.004616,[OrderedStatistic(items_base=frozenset({'Lime ...,"['0.2893081761006289', '11.963673373522273']","[0.2893081761006289, 11.963673373522273]",'11.963673373522273',"[0.2893081761006289, 11.963673373522273]"
1,"(Limes, Organic Cilantro)",0.005318,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.25728155339805825', '6.1049237170596395']","[0.25728155339805825, 6.1049237170596395]",'11.963673373522273',"[0.25728155339805825, 6.1049237170596395]"
2,"(Organic Zucchini, Organic Baby Spinach)",0.006723,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.2302405498281787', '3.1780849301767717']","[0.2302405498281787, 3.1780849301767717]",'11.963673373522273',"[0.2302405498281787, 3.1780849301767717]"
3,"(Organic Hass Avocado, Organic Cucumber)",0.005619,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.22764227642276422', '3.5448170731707314']","[0.22764227642276422, 3.5448170731707314]",'11.963673373522273',"[0.22764227642276422, 3.5448170731707314]"
4,"(Organic Hass Avocado, Organic Lemon)",0.006422,[OrderedStatistic(items_base=frozenset({'Organ...,"['0.23272727272727273', '3.624']","[0.23272727272727273, 3.624]",'11.963673373522273',"[0.23272727272727273, 3.624]"

In [79]:
ar['Confidence']

['0.2893081761006289', '11.963673373522273']

In [62]:
"'0.2893081761006289', '11.963673373522273'".split(',')

["'0.2893081761006289'", " '11.963673373522273'"]

In [63]:
int("'0.2893081761006289'")

ValueError: invalid literal for int() with base 10: "'0.2893081761006289'"